version: 2.1

references:
  workspace_root: &workspace_root
    ~/circleci-test
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  install-requirements: 
    description: "Install all of the requirements from the file specified."
    parameters:
      file: 
        type: string
        default: "requirements.txt"
    steps:
      - run: pip install -r << parameters.file >>
  run-tests:
    description: "Run all of the unit tests, duh..."
    steps:
      - run: python -m unittest

executors:
  python3-executor:
    docker:
      - image: circleci/python:3.7.2
    working_directory: *workspace_root

jobs:
  build:
    executor: python3-executor
    steps:
      - checkout
      - install-requirements
      - persist_to_workspace:
          root: *workspace_root
          paths: .
  test:
    executor: python3-executor
    steps:
      - *attach_workspace
      - run-tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
